### ISSUE TITLE
Hacer estructura básica de integración de API y ejemplos

### ISSUE THREAD

**Issue by andrsdt** [ISPP-Grupo5/BugaLink#157]

**Comment by pedparbas** [comment]
@andrsdt, ¿te importaría detallarme qué ejemplos has implementado? para reasignar las tareas.

**Comment by andrsdt** [comment]
> @andrsdt, ¿te importaría detallarme qué ejemplos has implementado? para reasignar las tareas.

Sí, básicamente todos los que aparecen en la carpeta `/hooks`:

**Vista de historial:**
* Historial de viajes: `/users/{userId}/trips/history?type={driver/passenger}`

**Vista principal:** 
* Información de mi usuario (para la foto): `/users/{userId}`
* Número de chats pendientes: `/users/{userId}/chats/pending/count`
* Número de solicitudes pendientes: `/users/{userId}/requests/pending/count`
* Carrusel de próximos viajes: `/users/{userId}/trips/upcoming`

**Vista de solicitudes:**
* Solicitudes pendientes: `/users/userId/trips?status=pending`

**Vista de recomendaciones:**
* Recomendaciones: `/trips/recommendations`

También ten en cuenta que las interfaces (`UserI`, `TripI`, `TripRequestI`) son muy provisionales y estamos pendientes de que los de backend nos den el modelo de datos definitivo. Lo más seguro es que el JSON que nos venga de su API de Django no tenga los mismos campos, así que habrá que cambiarlos también en las vistas
