### ISSUE TITLE
Endpoints vista “Hazte conductor”

### ISSUE THREAD

**Issue by gonmarmar5** [ISPP-Grupo5/BugaLink#249]
GET POST driver/docs -> Se sube la documentación. Cada solicitud hace el post de un documento y un atributo para identificar que documento es.

**Comment by andrsdt** [comment]
Todavía no está listo para integrarse, se tienen que hacer las siguientes cosas:

* Que al subir el primer documento se cree el `driver_id` y el perfil de driver del usuario pero aún no esté validado. El `user` podría tener un campo boolean `is_validated_driver` que indique si ya se han subido y validado todos sus campos de driver, es decir, si est apto para operar como driver en la plataforma

* Que la verificación de documentos se haga automáticamente, es decir, al subirlos se marcarían directamente como validados. El estado intermedio de "en revisión" se implementará más adelante porque implica que los administradores de bugalink tengamos acceso a algún panel para revisar y aceptar estos documentos, algo que ahora mismo no es prioritario y se escapa del alcance. De esta forma también facilitaríamos a los usuarios piloto que puedan convertirse en drivers sin tener que esperar a nuestra validación y puedan testear todas las funcionalidades.
