### ISSUE TITLE
Plan de pruebas

### ISSUE THREAD

**Issue by vicsotber** [ISPP-Grupo5/BugaLink#307]
Redacción de plan de pruebas detallado con tipo de pruebas que se deberían realizar como tests unitarios, de integración, etc. Esto es parte de lo que han pedido para la siguiente presentación.

**Comment by andrsdt** [comment]
Buen trabajo! He dejado un par de comentarios menores, principalmente para aclarar algunos términos que no terminaban de quedar claros. Haz los cambios y si están correctos lo podemos dar por terminado

**Comment by andrsdt** [comment]
Terminado, bien hecho :)
