### ISSUE TITLE
C&R [VISTA]: Detalles viaje 1

### ISSUE THREAD

**Issue by pedparbas** [ISPP-Grupo5/BugaLink#337]
Se deben conectar la [VISTA] así como los endpoints asociados.

En caso de ya estar conectados, se debe revisar que la conexión funciona y que están todos los endpoints asociados funcionando.

En caso de no haber algún endpoint funcionando se debe mantener la issue **abierta** hasta que se termine.

Si tenéis alguna duda sobre la implementación me podéis preguntar

Cualquier problema con el FRONT o BACK se procede de la siguiente manera: 
En la misma historia de la issue se debe añadir un comentario explicando el problema y se debe mencionar tanto al coordinador correspondiente como a mí con un @ (de forma que seamos notificados).

**Comment by andrsdt** [comment]
Ya lo he conectado, está pendiente de subir en una PR. Cierro para evitar confusiones.

NOTA: tras tambios en el alcance, DetailsOne pasa a llamarse Details y deja de existir DetailsTwo ya que era una vista que no aportaba nada nuevo (hemos quitado la funcionalidad de que puedas traer a varias personas contigo como pasajero)
