### ISSUE TITLE
Funcionalidad: Viajero recurrente

### ISSUE THREAD

**Issue by IgnacioPlanasTh** [ISPP-Grupo5/BugaLink#57]
Funcionalidad: permitir a un pasajero solicitar de manera recurrente un viaje. Esto implica: la creación de una entidad que relaccione a DriverRoutine con Passenger. La lógica asociada. Modificación del endpoint de solicitud de viaje para ver si es un viajeIndividual esporádico o recurrente

**Comment by andrsdt** [comment]
No se va a contemplar para el MVP, los viajeros tendrán que solicitar individualmente los viajes, no podrán "suscribirse" a una rutina por el momento.
